//go:build !ignore_autogenerated

/*
Copyright 2025 Matt Burdan.

SPDX-License-Identifier: MIT
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertCondition) DeepCopyInto(out *AlertCondition) {
	*out = *in
	if in.RowMatch != nil {
		in, out := &in.RowMatch, &out.RowMatch
		*out = make([]FieldMatch, len(*in))
		copy(*out, *in)
	}
	if in.RowCount != nil {
		in, out := &in.RowCount, &out.RowCount
		*out = new(RowCountCondition)
		**out = **in
	}
	if in.FieldThreshold != nil {
		in, out := &in.FieldThreshold, &out.FieldThreshold
		*out = new(FieldThresholdCondition)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertCondition.
func (in *AlertCondition) DeepCopy() *AlertCondition {
	if in == nil {
		return nil
	}
	out := new(AlertCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertNotify) DeepCopyInto(out *AlertNotify) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesNotify)
		**out = **in
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackNotify)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookNotify)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertNotify.
func (in *AlertNotify) DeepCopy() *AlertNotify {
	if in == nil {
		return nil
	}
	out := new(AlertNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertThrottle) DeepCopyInto(out *AlertThrottle) {
	*out = *in
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertThrottle.
func (in *AlertThrottle) DeepCopy() *AlertThrottle {
	if in == nil {
		return nil
	}
	out := new(AlertThrottle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedQuery) DeepCopyInto(out *DistributedQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedQuery.
func (in *DistributedQuery) DeepCopy() *DistributedQuery {
	if in == nil {
		return nil
	}
	out := new(DistributedQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedQueryList) DeepCopyInto(out *DistributedQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedQueryList.
func (in *DistributedQueryList) DeepCopy() *DistributedQueryList {
	if in == nil {
		return nil
	}
	out := new(DistributedQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedQuerySpec) DeepCopyInto(out *DistributedQuerySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedQuerySpec.
func (in *DistributedQuerySpec) DeepCopy() *DistributedQuerySpec {
	if in == nil {
		return nil
	}
	out := new(DistributedQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedQueryStatus) DeepCopyInto(out *DistributedQueryStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.NodeResults != nil {
		in, out := &in.NodeResults, &out.NodeResults
		*out = make([]NodeQueryResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedQueryStatus.
func (in *DistributedQueryStatus) DeepCopy() *DistributedQueryStatus {
	if in == nil {
		return nil
	}
	out := new(DistributedQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBridgeSpec) DeepCopyInto(out *EventBridgeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBridgeSpec.
func (in *EventBridgeSpec) DeepCopy() *EventBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(EventBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldMatch) DeepCopyInto(out *FieldMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldMatch.
func (in *FieldMatch) DeepCopy() *FieldMatch {
	if in == nil {
		return nil
	}
	out := new(FieldMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldThresholdCondition) DeepCopyInto(out *FieldThresholdCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldThresholdCondition.
func (in *FieldThresholdCondition) DeepCopy() *FieldThresholdCondition {
	if in == nil {
		return nil
	}
	out := new(FieldThresholdCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesNotify) DeepCopyInto(out *KubernetesNotify) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesNotify.
func (in *KubernetesNotify) DeepCopy() *KubernetesNotify {
	if in == nil {
		return nil
	}
	out := new(KubernetesNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeQueryResult) DeepCopyInto(out *NodeQueryResult) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Rows != nil {
		in, out := &in.Rows, &out.Rows
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeQueryResult.
func (in *NodeQueryResult) DeepCopy() *NodeQueryResult {
	if in == nil {
		return nil
	}
	out := new(NodeQueryResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAgent) DeepCopyInto(out *OsqueryAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAgent.
func (in *OsqueryAgent) DeepCopy() *OsqueryAgent {
	if in == nil {
		return nil
	}
	out := new(OsqueryAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OsqueryAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAgentList) DeepCopyInto(out *OsqueryAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OsqueryAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAgentList.
func (in *OsqueryAgentList) DeepCopy() *OsqueryAgentList {
	if in == nil {
		return nil
	}
	out := new(OsqueryAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OsqueryAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAgentSpec) DeepCopyInto(out *OsqueryAgentSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PackSelector != nil {
		in, out := &in.PackSelector, &out.PackSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EventBridge != nil {
		in, out := &in.EventBridge, &out.EventBridge
		*out = new(EventBridgeSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.EventBridgeResources.DeepCopyInto(&out.EventBridgeResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAgentSpec.
func (in *OsqueryAgentSpec) DeepCopy() *OsqueryAgentSpec {
	if in == nil {
		return nil
	}
	out := new(OsqueryAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAgentStatus) DeepCopyInto(out *OsqueryAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastConfigUpdate != nil {
		in, out := &in.LastConfigUpdate, &out.LastConfigUpdate
		*out = (*in).DeepCopy()
	}
	if in.AppliedPacks != nil {
		in, out := &in.AppliedPacks, &out.AppliedPacks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAgentStatus.
func (in *OsqueryAgentStatus) DeepCopy() *OsqueryAgentStatus {
	if in == nil {
		return nil
	}
	out := new(OsqueryAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAlert) DeepCopyInto(out *OsqueryAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAlert.
func (in *OsqueryAlert) DeepCopy() *OsqueryAlert {
	if in == nil {
		return nil
	}
	out := new(OsqueryAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OsqueryAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAlertList) DeepCopyInto(out *OsqueryAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OsqueryAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAlertList.
func (in *OsqueryAlertList) DeepCopy() *OsqueryAlertList {
	if in == nil {
		return nil
	}
	out := new(OsqueryAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OsqueryAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAlertSpec) DeepCopyInto(out *OsqueryAlertSpec) {
	*out = *in
	in.QuerySelector.DeepCopyInto(&out.QuerySelector)
	in.Condition.DeepCopyInto(&out.Condition)
	if in.Throttle != nil {
		in, out := &in.Throttle, &out.Throttle
		*out = new(AlertThrottle)
		(*in).DeepCopyInto(*out)
	}
	in.Notify.DeepCopyInto(&out.Notify)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAlertSpec.
func (in *OsqueryAlertSpec) DeepCopy() *OsqueryAlertSpec {
	if in == nil {
		return nil
	}
	out := new(OsqueryAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryAlertStatus) DeepCopyInto(out *OsqueryAlertStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastFired != nil {
		in, out := &in.LastFired, &out.LastFired
		*out = (*in).DeepCopy()
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryAlertStatus.
func (in *OsqueryAlertStatus) DeepCopy() *OsqueryAlertStatus {
	if in == nil {
		return nil
	}
	out := new(OsqueryAlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryPack) DeepCopyInto(out *OsqueryPack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryPack.
func (in *OsqueryPack) DeepCopy() *OsqueryPack {
	if in == nil {
		return nil
	}
	out := new(OsqueryPack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OsqueryPack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryPackList) DeepCopyInto(out *OsqueryPackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OsqueryPack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryPackList.
func (in *OsqueryPackList) DeepCopy() *OsqueryPackList {
	if in == nil {
		return nil
	}
	out := new(OsqueryPackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OsqueryPackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryPackSpec) DeepCopyInto(out *OsqueryPackSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]PackQuery, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryPackSpec.
func (in *OsqueryPackSpec) DeepCopy() *OsqueryPackSpec {
	if in == nil {
		return nil
	}
	out := new(OsqueryPackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsqueryPackStatus) DeepCopyInto(out *OsqueryPackStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployedToNodes != nil {
		in, out := &in.DeployedToNodes, &out.DeployedToNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsqueryPackStatus.
func (in *OsqueryPackStatus) DeepCopy() *OsqueryPackStatus {
	if in == nil {
		return nil
	}
	out := new(OsqueryPackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackQuery) DeepCopyInto(out *PackQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackQuery.
func (in *PackQuery) DeepCopy() *PackQuery {
	if in == nil {
		return nil
	}
	out := new(PackQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResult) DeepCopyInto(out *QueryResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResult.
func (in *QueryResult) DeepCopy() *QueryResult {
	if in == nil {
		return nil
	}
	out := new(QueryResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueryResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResultList) DeepCopyInto(out *QueryResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueryResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResultList.
func (in *QueryResultList) DeepCopy() *QueryResultList {
	if in == nil {
		return nil
	}
	out := new(QueryResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueryResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResultSpec) DeepCopyInto(out *QueryResultSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Rows != nil {
		in, out := &in.Rows, &out.Rows
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.Decorations != nil {
		in, out := &in.Decorations, &out.Decorations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResultSpec.
func (in *QueryResultSpec) DeepCopy() *QueryResultSpec {
	if in == nil {
		return nil
	}
	out := new(QueryResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResultStatus) DeepCopyInto(out *QueryResultStatus) {
	*out = *in
	if in.AcknowledgedAt != nil {
		in, out := &in.AcknowledgedAt, &out.AcknowledgedAt
		*out = (*in).DeepCopy()
	}
	if in.AlertsFired != nil {
		in, out := &in.AlertsFired, &out.AlertsFired
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResultStatus.
func (in *QueryResultStatus) DeepCopy() *QueryResultStatus {
	if in == nil {
		return nil
	}
	out := new(QueryResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuerySelector) DeepCopyInto(out *QuerySelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuerySelector.
func (in *QuerySelector) DeepCopy() *QuerySelector {
	if in == nil {
		return nil
	}
	out := new(QuerySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowCountCondition) DeepCopyInto(out *RowCountCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowCountCondition.
func (in *RowCountCondition) DeepCopy() *RowCountCondition {
	if in == nil {
		return nil
	}
	out := new(RowCountCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackNotify) DeepCopyInto(out *SlackNotify) {
	*out = *in
	out.WebhookSecretRef = in.WebhookSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackNotify.
func (in *SlackNotify) DeepCopy() *SlackNotify {
	if in == nil {
		return nil
	}
	out := new(SlackNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookNotify) DeepCopyInto(out *WebhookNotify) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookNotify.
func (in *WebhookNotify) DeepCopy() *WebhookNotify {
	if in == nil {
		return nil
	}
	out := new(WebhookNotify)
	in.DeepCopyInto(out)
	return out
}
