apiVersion: osquery.burdz.net/v1alpha1
kind: CompliancePolicy
metadata:
  name: cis-linux-baseline
spec:
  framework: cis
  version: "1.8.0"
  platform: linux

  controls:
    - id: "1.1.1"
      title: "Ensure mounting of cramfs filesystems is disabled"
      query: |
        SELECT name, status FROM kernel_modules WHERE name = 'cramfs';
      severity: low
      interval: 3600
      remediation: "Add 'install cramfs /bin/true' to /etc/modprobe.d/cramfs.conf"
      expectation:
        type: rowCount
        operator: equals
        value: 0

    - id: "1.4.1"
      title: "Ensure permissions on bootloader config are configured"
      query: |
        SELECT path, mode FROM file
        WHERE path IN ('/boot/grub/grub.cfg', '/boot/grub2/grub.cfg')
        AND mode != '0600';
      severity: high
      interval: 3600
      remediation: "Run: chmod 600 /boot/grub*/grub.cfg"

    - id: "5.1.1"
      title: "Ensure core dumps are disabled"
      query: |
        SELECT * FROM ulimit_info WHERE type = 'core' AND soft_limit != '0';
      severity: medium
      interval: 3600
      remediation: "Add '* hard core 0' to /etc/security/limits.conf"

    - id: "5.2.1"
      title: "Ensure SSH Protocol is set to 2"
      query: |
        SELECT * FROM ssh_configs WHERE key = 'Protocol' AND value != '2';
      severity: critical
      interval: 1800
      remediation: "Set 'Protocol 2' in /etc/ssh/sshd_config"

    - id: "5.2.4"
      title: "Ensure SSH X11 forwarding is disabled"
      query: |
        SELECT * FROM ssh_configs
        WHERE key = 'X11Forwarding' AND value = 'yes';
      severity: medium
      interval: 3600
      remediation: "Set 'X11Forwarding no' in /etc/ssh/sshd_config"

    - id: "5.2.8"
      title: "Ensure SSH root login is disabled"
      query: |
        SELECT * FROM ssh_configs
        WHERE key = 'PermitRootLogin' AND value != 'no';
      severity: critical
      interval: 1800
      remediation: "Set 'PermitRootLogin no' in /etc/ssh/sshd_config"

    - id: "6.1.2"
      title: "Ensure permissions on /etc/passwd are configured"
      query: |
        SELECT path, mode, uid, gid FROM file
        WHERE path = '/etc/passwd'
        AND (mode != '0644' OR uid != '0' OR gid != '0');
      severity: high
      interval: 3600
      remediation: "Run: chmod 644 /etc/passwd && chown root:root /etc/passwd"

    - id: "6.1.3"
      title: "Ensure permissions on /etc/shadow are configured"
      query: |
        SELECT path, mode FROM file
        WHERE path = '/etc/shadow'
        AND mode NOT IN ('0000', '0400', '0600', '0640');
      severity: critical
      interval: 3600
      remediation: "Run: chmod 640 /etc/shadow"

    - id: "6.2.1"
      title: "Ensure password fields are not empty"
      query: |
        SELECT username FROM shadow WHERE password_status = '';
      severity: critical
      interval: 3600
      remediation: "Lock or set passwords for all accounts"
